**This is a Basic Intro to Federated learning: computation on a remote virtual server**

In [1]:
!pip install syft==0.2.9

     |████████████████████████████████| 433 kB 8.2 MB/s 
     |████████████████████████████████| 126 kB 56.4 MB/s 
     |████████████████████████████████| 753.4 MB 6.1 kB/s 
     |████████████████████████████████| 66 kB 4.7 MB/s 
     |████████████████████████████████| 9.0 MB 13.7 MB/s 
     |████████████████████████████████| 449 kB 62.5 MB/s 
     |████████████████████████████████| 4.0 MB 42.7 MB/s 
     |████████████████████████████████| 57 kB 6.0 MB/s 
     |████████████████████████████████| 2.0 MB 54.9 MB/s 
     |████████████████████████████████| 200 kB 62.3 MB/s 
     |████████████████████████████████| 1.8 MB 49.8 MB/s 
     |████████████████████████████████| 20.1 MB 1.1 MB/s 
     |████████████████████████████████| 73 kB 2.1 MB/s 
     |████████████████████████████████| 484 kB 72.8 MB/s 
     |████████████████████████████████| 54 kB 3.2 MB/s 
     |████████████████████████████████| 79 kB 8.7 MB/s 
     |████████████████████████████████| 75 kB 4.3 MB/s 
     |████████████████████

In [3]:
import torch
import syft as sy

In [ ]:
#Basic Remote Execution in PySyft

In [20]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [21]:
y = x + x
x, y

(tensor([1, 2, 3, 4, 5]), tensor([ 2,  4,  6,  8, 10]))

In [22]:
hook = sy.TorchHook(torch)

In [23]:
client1 = sy.VirtualWorker(hook, id="client1")

In [24]:
client1._objects

{}

In [25]:
x = x.send(client1)

In [26]:
client1._objects

{92566898750: tensor([1, 2, 3, 4, 5])}

In [28]:
x.location, x.id

(<VirtualWorker id:client1 #objects:1>, 42518727057)

In [29]:
x.owner

<VirtualWorker id:me #objects:0>

In [30]:
x

(Wrapper)>[PointerTensor | me:42518727057 -> client1:92566898750]

In [31]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [ ]:
#Now send client 2

In [32]:
client2 = sy.VirtualWorker(hook, id="client2")

In [34]:
x = th.tensor([1,2,3,4,5])

In [35]:
x_ptr = x.send(client1, client2)

In [36]:
x_ptr.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])